# Generated by Django 4.2 on 2023-04-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
