# Generated by Django 4.2 on 2023-04-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcf', '0003_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimecode',
            name='created_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
